language: scala

# https://docs.travis-ci.com/user/notifications/#IRC-notification
notifications:
  irc:
    channels:
      - "chat.freenode.net#lichess"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
  slack:
    rooms:
      - lichess:sVTqlE0OQNMPq1n6qRnVnfrz
    on_success: change
    on_failure: always

# https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs
jdk:
  - oraclejdk8

install:
  - ./build-deps.sh

script:
  - sbt compile
  - sbt test
